function g = g_f(A,c,m,x)
%G_F
%    G = G_F(A1_1,A1_2,A2_1,A2_2,C1,C2,M,X1,X2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    27-Mar-2020 17:16:31

A1_1 = A(1,1);
A1_2 = A(1,2);
A2_1 = A(2,1);
A2_2 = A(2,2);
c1 = c(1);
c2 = c(2);
x1 = x(1);
x2 = x(2);


t2 = conj(c1);
t3 = conj(c2);
t4 = conj(x1);
t5 = conj(x2);
t6 = -t4;
t7 = -t5;
t8 = t2+t6;
t9 = t3+t7;
g = -(A1_1.*t8+A2_1.*t9).*(c1-x1)-(A1_2.*t8+A2_2.*t9).*(c2-x2)+m.^2;
