function D = D_f(x,m,c)
%D_F
%    D = D_F(C1,C2,M,X1,X2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    02-May-2020 19:04:18

c1 = c(1);
c2 = c(2);
x1 = x(1);
x2 = x(2);

D = -m+sqrt(abs(c1-x1).^2+abs(c2-x2).^2);
