function dD = dD_f(x,c)
%DD_F
%    DD = DD_F(C1,C2,X1,X2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    02-May-2020 19:04:18

c1 = c(1);
c2 = c(2);
x1 = x(1);
x2 = x(2);

t2 = -x1;
t3 = -x2;
t4 = c1+t2;
t5 = c2+t3;
t6 = abs(t4);
t7 = abs(t5);
t8 = t6.^2;
t9 = t7.^2;
t10 = t8+t9;
t11 = 1.0./sqrt(t10);
dD = [-t6.*t11.*sign(t4);-t7.*t11.*sign(t5)];
